name: Doctor

on: push

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-doctor-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-doctor-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1.2
          elixir-version: 1.14.2
      - run: mix deps.get
      - run: mix doctor
